name: Build / Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - arch: x64
            os: windows-latest
          - arch: arm64
            os: windows-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt
        env:
          PIP_NO_INDEX: false

      - name: Build with PyInstaller
        run: python build.py

      - name: Package zip
        shell: pwsh
        run: Compress-Archive -Path ../dist/O -DestinationPath Windows_${{ matrix.arch }}.zip

      - name: Create Release
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: Upload Release Asset
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} Windows_*.zip --clobber

  build-linux:
    strategy:
      matrix:
        include:
          - arch: x64
            os: ubuntu-22.04
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

  build-macos:
    strategy:
      matrix:
        include:
          - arch: arm64
            os: macos-14
            openssl_workaround: 'false'
          - arch: x64
            os: macos-15-intel
            openssl_workaround: 'true'
    runs-on: ${{ matrix.os }}
